/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;


import java.awt.MouseInfo;
import java.awt.Point;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import Diseño.*;
import entidades.*;
import java.awt.Color;
import javax.swing.JOptionPane;


/**
 *
 * @author HP
 */
public class FrmEstudiante extends javax.swing.JFrame {
    static int contador;
    private Hora hora;
    public static boolean estado;
    /**
     * Creates new form FrmEstudiante
     */
    public FrmEstudiante() {
        initComponents();
        movimiento();       
        jButton2.setBackground(Color.BLACK);
        jButton1.setBackground(Color.BLACK);

    }
    
    public FrmEstudiante(Estudiante estudiante) {
        initComponents();
        movimiento();
        this.estudiante = estudiante;
       rellenarCampos();

    }

    
    public void rellenarCampos(){
        hora = new Hora(jLabelHora);
        hora.start();
        
        jButton2.setBackground(Color.BLACK);
        jButton1.setBackground(Color.BLACK);
        
        
        labelNombre.setText(estudiante.getNombre());
        labelApellidos.setText(estudiante.getNombre());
        labelNombre.setText(estudiante.getApellidos());
        labelDirrecion.setText(estudiante.getDireccion());
    }
    
    public void movimiento(){
        int velocidad = 1;
        Timer timer;
        TimerTask tarea;
        int venil = velocidad*800;
        
        tarea = new TimerTask() {
            @Override
            public void run() {
                Icon icono;
                switch(contador){
                    case 0: 
                        contador = 1;
                        icono = new ImageIcon(getClass().getResource("/imagenes/blanco_rojo.png"));
                        jLabel3.setIcon(icono);
                        break;
                    case 1: 
                        contador = 2;
                        icono = new ImageIcon(getClass().getResource("/imagenes/blanco_amarillo.png"));
                        jLabel3.setIcon(icono);
                        break;
                    case 2:
                        contador = 0;
                        icono = new ImageIcon(getClass().getResource("/imagenes/blanco_verde.png"));
                        jLabel3.setIcon(icono);
                        break;  
                }
                
            }
        };
        timer = new Timer();
        timer.scheduleAtFixedRate(tarea, venil, venil);
    }
    
      public void estado(){
        if(estado){
            FrmCalificacion califi = new FrmCalificacion();
            califi.setVisible(true);
        }else{
            JOptionPane.showInternalMessageDialog(null,"Aún no se matriculo en ningun curso");

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelCarrera = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelApellidos = new javax.swing.JLabel();
        labelDirrecion = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blanco_rojo.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-x_30.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 778, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 920, 42);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCarrera.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        labelCarrera.setText("Ingenieria de sistemas");
        jPanel1.add(labelCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, 30));

        labelNombre.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        labelNombre.setText("Jonathan Smith");
        jPanel1.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 150, -1));

        labelApellidos.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        labelApellidos.setText("Mostacero Camacho");
        jPanel1.add(labelApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 130, -1));

        labelDirrecion.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        labelDirrecion.setText("Hipolito Unanue Mz \"K\"");
        jPanel1.add(labelDirrecion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, -1, 30));

        jLabelHora.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHora.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabelHora.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLabelHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 110, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_u.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 470, -1));

        jButton1.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Calificaciones");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, 150, 40));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Matricular");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 150, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calificaciones.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 200, 170));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/matricula.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 180, 170));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 40, 920, 560);

        setSize(new java.awt.Dimension(919, 615));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int xx,xy;
    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
         Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - xx, point.y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
       xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        estado();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        FrmAlumno estudiante = new FrmAlumno();
            estudiante.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        dispose();
        FrmLoginEstudiante c = new FrmLoginEstudiante();
        c.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEstudiante().setVisible(true);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelApellidos;
    private javax.swing.JLabel labelCarrera;
    private javax.swing.JLabel labelDirrecion;
    private javax.swing.JLabel labelNombre;
    // End of variables declaration//GEN-END:variables
    private Estudiante estudiante;

}
