/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import entidades.*;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author HP
 */
public class FrmLoginEstudiante extends javax.swing.JFrame {

    private ArrayList<Matricula> matriculados;

    /**
     * Creates new form FrmLoginEstudiante
     */
    public FrmLoginEstudiante() {
        initComponents();
        matriculados = FrmAlumno.matriculas;
    }

    public boolean Verificar(int matriculado) {
        boolean estado = true;
        try {

            for (int j = 0; j < matriculados.get(matriculado).getAsignaturas().size(); j++) {
                
                if (matriculados.get(matriculado).getAsignaturas().get(j).getContador() == 4) {
                    estado = false;
//                    System.out.println(matriculados.get(matriculado).getAlumno().getNombre());
                }
            }

        } catch (Exception e) {
        }
        return estado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alumno (1).png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 170, 150));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-cerrar.png"))); // NOI18N
        jLabel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 40, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel4.setText("Usuario :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        txtCorreo.setBackground(new java.awt.Color(204, 204, 204));
        txtCorreo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(51, 51, 51));
        txtCorreo.setBorder(null);
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCorreoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCorreoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoKeyTyped(evt);
            }
        });
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 190, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel5.setText("Contraseña :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        txtContraseña.setBackground(new java.awt.Color(204, 204, 204));
        txtContraseña.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(0, 0, 0));
        txtContraseña.setBorder(null);
        txtContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtContraseñaMouseClicked(evt);
            }
        });
        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 190, 30));

        jToggleButton1.setBackground(new java.awt.Color(153, 153, 255));
        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton1.setText("Ingresar");
        jToggleButton1.setBorder(null);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 120, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 210, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 210, 10));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen_fondo_estudiante.png"))); // NOI18N
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel3MouseDragged(evt);
            }
        });
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 430));

        setSize(new java.awt.Dimension(413, 430));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int x, y;
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        dispose();
        FrmPrincipalN c = new FrmPrincipalN();
        c.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseDragged
        Point poin = MouseInfo.getPointerInfo().getLocation();
        setLocation(poin.x - x, poin.y - y);
    }//GEN-LAST:event_jLabel3MouseDragged

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        int veri = 0;
        int cont = -1;

        for (int i = 0; i < FrmRegistrarEstudiante.estudiantes.size(); i++) {
            if (txtCorreo.getText().equals(FrmRegistrarEstudiante.estudiantes.get(i).getUsuario())
                    && txtContraseña.getText().equals(FrmRegistrarEstudiante.estudiantes.get(i).getContra())) {
                cont = i;
                veri=i;
            }

        }
        if (cont != -1) {
            FrmEstudiante.estado = false;
            for (int i = 0; i < matriculados.size(); i++) {

                if (matriculados.get(i).getAlumno().getUsuario().equals(txtCorreo.getText())
                        && matriculados.get(i).getAlumno().getContra().equals(txtContraseña.getText())) {
                    FrmCalificacion.cursos = matriculados.get(i).cursos();
                    FrmCalificacion.notas = matriculados.get(i).notas();
                    FrmEstudiante.estado = true;
//                    JOptionPane.showMessageDialog(null,"Posi : "+i +"\nNombre "+);
//                    veri = i;
                }

            }
            if (Verificar(veri)) {
                if (cont != -1) {
                    dispose();
                    JOptionPane.showMessageDialog(null, "Bienvenido " + FrmRegistrarEstudiante.estudiantes.get(cont).getNombre() + " "
                            + FrmRegistrarEstudiante.estudiantes.get(cont).getApellidos(), "Mensaje", 1);
//            FrmCalificacion.cursos=FrmRegistrarEstudiante.estudiantes.get(cont).
                    FrmAlumno.alumno = FrmRegistrarEstudiante.estudiantes.get(cont);
                    FrmEstudiante.nombre = FrmRegistrarEstudiante.estudiantes.get(cont).getNombre();
                    FrmEstudiante.apellidos = FrmRegistrarEstudiante.estudiantes.get(cont).getApellidos();
                    FrmEstudiante.direccion = FrmRegistrarEstudiante.estudiantes.get(cont).getDireccion();

                    FrmEstudiante c = new FrmEstudiante();
                    c.setVisible(true);

                } else {
                    JOptionPane.showMessageDialog(null, "Datos Invalidos. Vuelva a escribir", "Mensaje", 0);
                    txtCorreo.setText(null);
                    txtContraseña.setText(null);
                }

                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Estimado Alumno, Usted ha sido retirado de la universidad\n"
                        + "por llevar por cuarta vez el mismo curso, Bendiciones");
            }

        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void txtContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraseñaMouseClicked
        txtContraseña.setText(null);
    }//GEN-LAST:event_txtContraseñaMouseClicked

    private void txtCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyReleased
        //txtCorreo.setHorizontalAlignment(SwingConstants.CENTER);
        //JOptionPane.showMessageDialog(null,"Hola");
    }//GEN-LAST:event_txtCorreoKeyReleased

    private void txtCorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyPressed
        //txtCorreo.setHorizontalAlignment(SwingConstants.CENTER);
    }//GEN-LAST:event_txtCorreoKeyPressed

    private void txtCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyTyped

    }//GEN-LAST:event_txtCorreoKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txtCorreo.setHorizontalAlignment(SwingConstants.CENTER);
        txtContraseña.setHorizontalAlignment(SwingConstants.CENTER);
    }//GEN-LAST:event_formWindowOpened

    private void jLabel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLoginEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLoginEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLoginEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLoginEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLoginEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables

}
