/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import ModelosTabla.ModeloMatricula;
import entidades.Asignatura;
import entidades.AsignaturaCalificacion;
import entidades.Matricula;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class FrmMatriculas extends javax.swing.JFrame {
    ArrayList<Matricula> matriculas;
    /**
     * Creates new form FrmMatriculas
     */
    public FrmMatriculas() {
        initComponents();
        matriculas = FrmAlumno.matriculas;
        jTable1.setModel(new ModeloMatricula(matriculas));
    }
    
    public void elegirAsignatura(){
        try {
        int row = jTable1.getSelectedRow();
            String apellido = String.valueOf(jTable1.getValueAt(row, 1));  
            if (!(row == -1)) {
                //recorro un ciclo para saber la asignatura por codigo
                for (int j = 0; j < matriculas.size(); j++) {
                    if (matriculas.get(j).getAlumno().getApellidos().equals(apellido)) {
                        //Añado la asignatura matriculada
                        llenarCurso(matriculas.get(j).getAsignaturas());
                        JOptionPane.showMessageDialog(null, "Asignatura Seleccionada!", "Mensaje", 1);
                        //sumo los creditos
                    }
                }

            } else {
                JOptionPane.showMessageDialog(null, "Seleccione una fila de la tabla", "Mensaje", 2);
            }
        } catch (Exception e) {
        }
    }
    
    public void llenarCurso(ArrayList<AsignaturaCalificacion> asignaturas){
        String mensaje = "  CURSOS MATRICULADOS\n\n";
        String mensaje2 = " CRÉDITOS\n\n";
        for (int i = 0; i < asignaturas.size(); i++) {
            mensaje +="      "+ (i+1) +"-"+ asignaturas.get(i).getAsignatura().getNombre()+"\n";
            mensaje2 +=" N° "+asignaturas.get(i).getAsignatura().getCreditos()+"\n";
        }
        jTextArea1.setText(mensaje);
        jTextArea2.setText(mensaje2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 680, 176));

        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 320, 200));

        jButton3.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jButton3.setText("ATRÁS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 480, -1, -1));

        jTextArea2.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 210, 200));

        jButton1.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jButton1.setText("VISUALIZAR ASIGNATURAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabel1.setText("ALUMNOS MATRICULADOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        FrmAdministrador c = new FrmAdministrador();
        c.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        elegirAsignatura();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
